// Error names
module.exports = {
  USER_CAN_NOT_PERFORM_THIS_ACTION: 'USER_CAN_NOT_PERFORM_THIS_ACTION',
  USER_DOES_NOT_EXISTS: 'USER_DOES_NOT_EXISTS',
  ERROR_USERNAME_OR_PASSWORD: 'ERROR_USERNAME_OR_PASSWORD',
  USER_ALREADY_CONFIRMED: 'USER_ALREADY_CONFIRMED',
  RESET_PASSWORD_CODE_NOT_EXISTS: 'RESET_PASSWORD_CODE_NOT_EXISTS',
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
  ROLE_NAME_DOES_NOT_EXISTS: 'ROLE_NAME_DOES_NOT_EXISTS',
  PARAMS_REQUIRED: 'PARAMS_REQUIRED',
  DATABASE_ERROR: 'DATABASE_ERROR',
};
